services:
  - type: web
    name: test-applepaynodeweb
    runtime: node
    plan: free
    buildCommand: yarn install --frozen-lockfile || yarn install
    startCommand: yarn start
    envVars:
      - key: NODE_VERSION
        value: 20.19.2
