services:
  - type: web
    name: test-applepaynodeweb
    runtime: node
    plan: free
    buildCommand: npm ci --legacy-peer-deps || npm install --legacy-peer-deps
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 20.19.2
